//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.09.26 at 09:58:04 PM BRT 
//


package com.reviewboard.api.model.reviewrequests;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlMixed;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice maxOccurs="unbounded" minOccurs="0">
 *         &lt;element ref="{}href"/>
 *         &lt;element ref="{}links"/>
 *         &lt;element ref="{}method"/>
 *         &lt;element ref="{}title"/>
 *         &lt;element ref="{}branch"/>
 *         &lt;element ref="{}bugs_closed"/>
 *         &lt;element ref="{}changenum"/>
 *         &lt;element ref="{}description"/>
 *         &lt;element ref="{}id"/>
 *         &lt;element ref="{}last_updated"/>
 *         &lt;element ref="{}public"/>
 *         &lt;element ref="{}status"/>
 *         &lt;element ref="{}summary"/>
 *         &lt;element ref="{}target_groups"/>
 *         &lt;element ref="{}target_people"/>
 *         &lt;element ref="{}testing_done"/>
 *         &lt;element ref="{}time_added"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "content"
})
@XmlRootElement(name = "item")
public class Item {

    @XmlElementRefs({
        @XmlElementRef(name = "target_people", type = JAXBElement.class),
        @XmlElementRef(name = "summary", type = JAXBElement.class),
        @XmlElementRef(name = "href", type = JAXBElement.class),
        @XmlElementRef(name = "description", type = JAXBElement.class),
        @XmlElementRef(name = "last_updated", type = JAXBElement.class),
        @XmlElementRef(name = "method", type = JAXBElement.class),
        @XmlElementRef(name = "branch", type = JAXBElement.class),
        @XmlElementRef(name = "id", type = JAXBElement.class),
        @XmlElementRef(name = "time_added", type = JAXBElement.class),
        @XmlElementRef(name = "testing_done", type = JAXBElement.class),
        @XmlElementRef(name = "changenum", type = Changenum.class),
        @XmlElementRef(name = "status", type = JAXBElement.class),
        @XmlElementRef(name = "target_groups", type = JAXBElement.class),
        @XmlElementRef(name = "title", type = JAXBElement.class),
        @XmlElementRef(name = "bugs_closed", type = JAXBElement.class),
        @XmlElementRef(name = "links", type = Links.class),
        @XmlElementRef(name = "public", type = JAXBElement.class)
    })
    @XmlMixed
    protected List<Object> content;

    /**
     * Gets the value of the content property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the content property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getContent().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link Array }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link Changenum }
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link Array }{@code >}
     * {@link JAXBElement }{@code <}{@link Array }{@code >}
     * {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
     * {@link Links }
     * 
     * 
     */
    public List<Object> getContent() {
        if (content == null) {
            content = new ArrayList<Object>();
        }
        return this.content;
    }

}
