//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.09.26 at 09:58:04 PM BRT 
//


package com.reviewboard.api.model.reviewrequests;

import java.math.BigInteger;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.reviewboard.api.model.reviewrequests package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Summary_QNAME = new QName("", "summary");
    private final static QName _TimeAdded_QNAME = new QName("", "time_added");
    private final static QName _Status_QNAME = new QName("", "status");
    private final static QName _TargetPeople_QNAME = new QName("", "target_people");
    private final static QName _Stat_QNAME = new QName("", "stat");
    private final static QName _Id_QNAME = new QName("", "id");
    private final static QName _Title_QNAME = new QName("", "title");
    private final static QName _TargetGroups_QNAME = new QName("", "target_groups");
    private final static QName _BugsClosed_QNAME = new QName("", "bugs_closed");
    private final static QName _Description_QNAME = new QName("", "description");
    private final static QName _TestingDone_QNAME = new QName("", "testing_done");
    private final static QName _ReviewRequests_QNAME = new QName("", "review_requests");
    private final static QName _Branch_QNAME = new QName("", "branch");
    private final static QName _LastUpdated_QNAME = new QName("", "last_updated");
    private final static QName _Method_QNAME = new QName("", "method");
    private final static QName _Public_QNAME = new QName("", "public");
    private final static QName _Href_QNAME = new QName("", "href");
    private final static QName _TotalResults_QNAME = new QName("", "total_results");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.reviewboard.api.model.reviewrequests
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Update }
     * 
     */
    public Update createUpdate() {
        return new Update();
    }

    /**
     * Create an instance of {@link Rsp }
     * 
     */
    public Rsp createRsp() {
        return new Rsp();
    }

    /**
     * Create an instance of {@link Array }
     * 
     */
    public Array createArray() {
        return new Array();
    }

    /**
     * Create an instance of {@link Links }
     * 
     */
    public Links createLinks() {
        return new Links();
    }

    /**
     * Create an instance of {@link Diffs }
     * 
     */
    public Diffs createDiffs() {
        return new Diffs();
    }

    /**
     * Create an instance of {@link Repository }
     * 
     */
    public Repository createRepository() {
        return new Repository();
    }

    /**
     * Create an instance of {@link Self }
     * 
     */
    public Self createSelf() {
        return new Self();
    }

    /**
     * Create an instance of {@link Create }
     * 
     */
    public Create createCreate() {
        return new Create();
    }

    /**
     * Create an instance of {@link Next }
     * 
     */
    public Next createNext() {
        return new Next();
    }

    /**
     * Create an instance of {@link LastUpdate }
     * 
     */
    public LastUpdate createLastUpdate() {
        return new LastUpdate();
    }

    /**
     * Create an instance of {@link Reviews }
     * 
     */
    public Reviews createReviews() {
        return new Reviews();
    }

    /**
     * Create an instance of {@link Draft }
     * 
     */
    public Draft createDraft() {
        return new Draft();
    }

    /**
     * Create an instance of {@link Submitter }
     * 
     */
    public Submitter createSubmitter() {
        return new Submitter();
    }

    /**
     * Create an instance of {@link Screenshots }
     * 
     */
    public Screenshots createScreenshots() {
        return new Screenshots();
    }

    /**
     * Create an instance of {@link Delete }
     * 
     */
    public Delete createDelete() {
        return new Delete();
    }

    /**
     * Create an instance of {@link Item }
     * 
     */
    public Item createItem() {
        return new Item();
    }

    /**
     * Create an instance of {@link Changenum }
     * 
     */
    public Changenum createChangenum() {
        return new Changenum();
    }

    /**
     * Create an instance of {@link ArrayElement }
     * 
     */
    public ArrayElement createArrayElement() {
        return new ArrayElement();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "summary")
    public JAXBElement<String> createSummary(String value) {
        return new JAXBElement<String>(_Summary_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "time_added")
    public JAXBElement<String> createTimeAdded(String value) {
        return new JAXBElement<String>(_TimeAdded_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "status")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createStatus(String value) {
        return new JAXBElement<String>(_Status_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Array }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "target_people")
    public JAXBElement<Array> createTargetPeople(Array value) {
        return new JAXBElement<Array>(_TargetPeople_QNAME, Array.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "stat")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createStat(String value) {
        return new JAXBElement<String>(_Stat_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "id")
    public JAXBElement<BigInteger> createId(BigInteger value) {
        return new JAXBElement<BigInteger>(_Id_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "title")
    public JAXBElement<String> createTitle(String value) {
        return new JAXBElement<String>(_Title_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Array }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "target_groups")
    public JAXBElement<Array> createTargetGroups(Array value) {
        return new JAXBElement<Array>(_TargetGroups_QNAME, Array.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Array }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "bugs_closed")
    public JAXBElement<Array> createBugsClosed(Array value) {
        return new JAXBElement<Array>(_BugsClosed_QNAME, Array.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "description")
    public JAXBElement<String> createDescription(String value) {
        return new JAXBElement<String>(_Description_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "testing_done")
    public JAXBElement<String> createTestingDone(String value) {
        return new JAXBElement<String>(_TestingDone_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Array }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "review_requests")
    public JAXBElement<Array> createReviewRequests(Array value) {
        return new JAXBElement<Array>(_ReviewRequests_QNAME, Array.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "branch")
    public JAXBElement<String> createBranch(String value) {
        return new JAXBElement<String>(_Branch_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "last_updated")
    public JAXBElement<String> createLastUpdated(String value) {
        return new JAXBElement<String>(_LastUpdated_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "method")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createMethod(String value) {
        return new JAXBElement<String>(_Method_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "public")
    public JAXBElement<BigInteger> createPublic(BigInteger value) {
        return new JAXBElement<BigInteger>(_Public_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "href")
    public JAXBElement<String> createHref(String value) {
        return new JAXBElement<String>(_Href_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "total_results")
    public JAXBElement<BigInteger> createTotalResults(BigInteger value) {
        return new JAXBElement<BigInteger>(_TotalResults_QNAME, BigInteger.class, null, value);
    }

}
