//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.09.26 at 07:01:33 PM BRT 
//


package com.reviewboard.api.model.reviewresource;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}diff_comments" minOccurs="0"/>
 *         &lt;element ref="{}self"/>
 *         &lt;choice>
 *           &lt;sequence>
 *             &lt;element ref="{}update"/>
 *             &lt;element ref="{}screenshot_comments"/>
 *             &lt;element ref="{}user"/>
 *             &lt;element ref="{}replies"/>
 *             &lt;element ref="{}delete"/>
 *           &lt;/sequence>
 *           &lt;sequence>
 *             &lt;element ref="{}review_draft"/>
 *             &lt;element ref="{}create"/>
 *           &lt;/sequence>
 *         &lt;/choice>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "diffComments",
    "self",
    "update",
    "screenshotComments",
    "user",
    "replies",
    "delete",
    "reviewDraft",
    "create"
})
@XmlRootElement(name = "links")
public class Links {

    @XmlElement(name = "diff_comments")
    protected DiffComments diffComments;
    @XmlElement(required = true)
    protected Self self;
    protected Update update;
    @XmlElement(name = "screenshot_comments")
    protected ScreenshotComments screenshotComments;
    protected User user;
    protected Replies replies;
    protected Delete delete;
    @XmlElement(name = "review_draft")
    protected ReviewDraft reviewDraft;
    protected Create create;

    /**
     * Gets the value of the diffComments property.
     * 
     * @return
     *     possible object is
     *     {@link DiffComments }
     *     
     */
    public DiffComments getDiffComments() {
        return diffComments;
    }

    /**
     * Sets the value of the diffComments property.
     * 
     * @param value
     *     allowed object is
     *     {@link DiffComments }
     *     
     */
    public void setDiffComments(DiffComments value) {
        this.diffComments = value;
    }

    /**
     * Gets the value of the self property.
     * 
     * @return
     *     possible object is
     *     {@link Self }
     *     
     */
    public Self getSelf() {
        return self;
    }

    /**
     * Sets the value of the self property.
     * 
     * @param value
     *     allowed object is
     *     {@link Self }
     *     
     */
    public void setSelf(Self value) {
        this.self = value;
    }

    /**
     * Gets the value of the update property.
     * 
     * @return
     *     possible object is
     *     {@link Update }
     *     
     */
    public Update getUpdate() {
        return update;
    }

    /**
     * Sets the value of the update property.
     * 
     * @param value
     *     allowed object is
     *     {@link Update }
     *     
     */
    public void setUpdate(Update value) {
        this.update = value;
    }

    /**
     * Gets the value of the screenshotComments property.
     * 
     * @return
     *     possible object is
     *     {@link ScreenshotComments }
     *     
     */
    public ScreenshotComments getScreenshotComments() {
        return screenshotComments;
    }

    /**
     * Sets the value of the screenshotComments property.
     * 
     * @param value
     *     allowed object is
     *     {@link ScreenshotComments }
     *     
     */
    public void setScreenshotComments(ScreenshotComments value) {
        this.screenshotComments = value;
    }

    /**
     * Gets the value of the user property.
     * 
     * @return
     *     possible object is
     *     {@link User }
     *     
     */
    public User getUser() {
        return user;
    }

    /**
     * Sets the value of the user property.
     * 
     * @param value
     *     allowed object is
     *     {@link User }
     *     
     */
    public void setUser(User value) {
        this.user = value;
    }

    /**
     * Gets the value of the replies property.
     * 
     * @return
     *     possible object is
     *     {@link Replies }
     *     
     */
    public Replies getReplies() {
        return replies;
    }

    /**
     * Sets the value of the replies property.
     * 
     * @param value
     *     allowed object is
     *     {@link Replies }
     *     
     */
    public void setReplies(Replies value) {
        this.replies = value;
    }

    /**
     * Gets the value of the delete property.
     * 
     * @return
     *     possible object is
     *     {@link Delete }
     *     
     */
    public Delete getDelete() {
        return delete;
    }

    /**
     * Sets the value of the delete property.
     * 
     * @param value
     *     allowed object is
     *     {@link Delete }
     *     
     */
    public void setDelete(Delete value) {
        this.delete = value;
    }

    /**
     * Gets the value of the reviewDraft property.
     * 
     * @return
     *     possible object is
     *     {@link ReviewDraft }
     *     
     */
    public ReviewDraft getReviewDraft() {
        return reviewDraft;
    }

    /**
     * Sets the value of the reviewDraft property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReviewDraft }
     *     
     */
    public void setReviewDraft(ReviewDraft value) {
        this.reviewDraft = value;
    }

    /**
     * Gets the value of the create property.
     * 
     * @return
     *     possible object is
     *     {@link Create }
     *     
     */
    public Create getCreate() {
        return create;
    }

    /**
     * Sets the value of the create property.
     * 
     * @param value
     *     allowed object is
     *     {@link Create }
     *     
     */
    public void setCreate(Create value) {
        this.create = value;
    }

}
